### ISSUE TITLE
Add ingressClassName field

### ISSUE THREAD

**Issue by adubkov** [argoproj-labs/argocd-operator#652] opened 2022-05-14 09:58 UTC
We need to add `ingressClassName` support to customize ingress.

**Comment by adubkov** [comment] 2022-05-14 10:02
and `host`

**Comment by ishitasequeira** [comment] 2022-05-17 05:13
Hi @adubkov, I guess this [PR](https://github.com/argoproj-labs/argocd-operator/pull/636/) might suffice the request. WDYT?

**Comment by adubkov** [comment] 2022-05-17 08:46
@ishitasequeira Yes, it looks like it would solve this issue.

**Comment by ishitasequeira** [comment] 2022-05-26 15:31
closing this as its a duplicate of [626](https://github.com/argoproj-labs/argocd-operator/issues/626)

**Closed by ishitasequeira** 2022-05-26 15:31 UTC
